# yazi keymap configuration
# https://yazi-rs.github.io/docs/configuration/keymap

[[manager.prepend_keymap]]
on = ["<C-h>"]
run = "hidden toggle"
desc = "Toggle hidden files"

[[manager.prepend_keymap]]
on = ["T"]
run = "shell 'eza --tree --level=3 --icons \"$@\"' --block"
desc = "Show tree view"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Go to Downloads"

[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/Code"
desc = "Go to Code"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/.dotfiles"
desc = "Go to dotfiles"
